import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}; 

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode; }>) => {
    return (
        <html lang="en">
            <head>
                <link href="https://fonts.googleapis.com/css2?family=Parkinsans:wght@300..800&display=swap" rel="stylesheet" />
            </head>
            <body>
                {children}
            </body>
        </html>
    );
}

export default RootLayout